### PR TITLE
Keikodoc

### PR DESCRIPTION
**Pull request by keikhara**
@Microsoft/omsagent-devs 

Updated the OMS Agent for Linux README to reflect the latest 75 release. 

please sign-off asap.

### CODE REVIEW

**Comment by lagalbra** [comment]
I would recommend squashing these commits into a single commit before you merge, but other than that it looks fine.

**Comment by vrdmr** [comment]
@keikhara Could you please squash all the commits into one commit and then rebase master before the commit?

`git rebase -i HEAD~8` and then picking the one commit for others to squash together would doo the trick. Please refer https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

You can also use the UI to squash - https://github.com/blog/2141-squash-your-commits

**Comment by keikhara** [comment]
something messed up. will close and delete.

**Comment by jeffaco** [comment]
Note that, from the last time Keiko needed help squashing commit messages, changes were in flight for ostc-docs specifically on squashing commits. These have now been reviewed and committed to the ostc-docs repository under the workflow (common operations).

See [here](https://github.com/Microsoft/ostc-docs/blob/master/workflow-workflow.md#squashing-commit-messages) for details.

**Comment by keikhara** [comment]
Thanks will do this.

**Pull request closed without merging**
