### PR TITLE
Updating logging to provide better error message during Meta config creation

### PR DESCRIPTION
**Pull request by mbreakey3**
- Updating one of the error logs during meta config creation to print the actual error code.
- Moving the check for the existence of the metaconfig.py file to happen before we call the metaconfig.py file

### CODE REVIEW

**Comment by mbreakey3** [comment]
@NarineM  - would you mind reviewing this? We want to get it in for tonight's daily build if possible.

**Comment by mbreakey3** [comment]
Done

**Comment by mbreakey3** [comment]
@NarineM - fixed whitespace

**Comment by NarineM** [comment]
thanks! Go ahead with merging.

**Comment by mbreakey3** [comment]
I don't have write access - can you merge?

**Pull request merged**
