### PR TITLE
Fix libmysqlclient dependency in the build system

### PR DESCRIPTION
**Pull request by NarineM**
Fix libmysqlclient dependency in the build system

### CODE REVIEW

**Comment by jeffaco** [comment]
I do NOT approve this, and this should not be committed. You'll need to revert it.

We don't handle dependencies in our build and dev systems this way. If you need a package installed, we handle that during system creation. That is part of what our systems team does. Otherwise, you can end up with random versions of packages that we can't necessarily easily reconstruct from prior versions.

Did you get sign-off on this? How do you want to go about reverting this?

**Comment by NarineM** [comment]
This is not a package, these are the client native lib  that is needed temparaly for only building the gem for given platform. It needs to be compiled runtime and it never is used later on. This fixes the build till we find better way.

**Comment by NarineM** [comment]
Is there a way to include this particular lib with Jenkins build system? If there is once it is added to jenkin I will remove this part.

**Comment by jeffaco** [comment]
I will discuss with Robbie shortly.

**Pull request merged**
