### PR TITLE
Add DSC Diagnostics Script

### PR DESCRIPTION
**Pull request by zjalali**
Adding a script to collect some logs for DSC diagnostics.

### CODE REVIEW

**Comment by zjalali** [comment]
Sure. I expect a few more changes in the script as well. Once that's finalized, I'll zip this and update the tar file.

**Comment by zjalali** [comment]
@lagalbra ready for final review.

**Comment by lagalbra** [comment]
@zjalali please squash all of your commits into a single commit before merging this PR.

**Comment by zjalali** [comment]
@lagalbra I don't have access to merge this yet.

**Pull request merged**
