### PR TITLE
Refactor proxy related test cases

### PR DESCRIPTION
**Pull request by lagalbra**
Move proxy testing to specific tests in agent_maintenance_script_systest.rb
Call check_proxy_server_working before all system tests involving proxy.

### CODE REVIEW

**Comment by lagalbra** [comment]
@Microsoft/omsagent-devs @NarineM @sugr4 I'm creating a pull request for this in case we do not commit changes including the new proxy server by the Jenkins build tonight.

**Comment by NarineM** [comment]
@lagalbra , we already have the new proxy server setup so disabling tests part needs to be removed from this PR.

**Comment by lagalbra** [comment]
Commit made just now disables only the test that is failing against the new proxy server: `test_onboard_proxy_failure`. I have emailed Kris to fix it.

**Comment by NarineM** [comment]
please update the title from "disable tests" to be "disable proxy with password test".

**Comment by NarineM** [comment]
I updated , you can go ahead with merging. thanks.

**Comment by lagalbra** [comment]
I'm double-checking that the tests pass, and then I will merge.

**Comment by lagalbra** [comment]
The new proxy server is now failing like the previous one on the curl command. If it isn't resolved in the next 20 minutes, we will disable the system tests for tonight's build.

**Comment by lagalbra** [comment]
All tests are passing now. Will merge as soon as Travis completes.

**Comment by lagalbra** [comment]
Since this commit is not necessary for getting a passing build tonight, I may wait until morning to merge it (just in case).

**Pull request merged**
