### PR TITLE
remove mysql ruby plugin from the bundle

### PR DESCRIPTION
**Pull request by NarineM**
Temp removing MySQL gem and the plugin from the bundle till the issue with CentOS 5's libmysqlclient compatability withUbuntu 14/16 is resolved.
@robbiezhang

### CODE REVIEW

**Comment by robbiezhang** [comment]
@Microsoft/omsagent-devs

**Comment by robbiezhang** [comment]
remove the removed ruby and config files from the 
installer/datafiles/base_omsagent.data

**Comment by robbiezhang** [comment]
Remove the install mysql gem in build/buildRuby.sh

**Comment by NarineM** [comment]
Canceling this. Anurag suggested to keep it the way it is.

**Comment by agup006** [comment]
We should keep this work item open, but not have as a deliverable for
Ignite release

**Pull request closed without merging**
