### PR TITLE
Convert log collector doc to markdown

### PR DESCRIPTION
**Pull request by lagalbra**
Added pictures and rewording for extension

@Microsoft/omsagent-devs  - FYI this doc describes a script which should be used for troubleshooting customer issues. Feel free to contribute to the script and to the documentation.

### CODE REVIEW

**Comment by keikhara** [comment]
@lagalbra  This is a customer facing log collection script. As I did initially, please remove paragraph which will confuse the customer when running the script. (This will be paragraph before Log Collector Installation Steps) Other than that, adding pictures is good. Also please remove the title containers since we will add more plug-in logs in here as well. It should be Linux Agent log Collector.

**Comment by lagalbra** [comment]
Removed the "different OMS Linux Agent type" section, as well as the titles which indicated Container rather than OMSAgent in general.

**Comment by keikhara** [comment]
@lagalbra Please remove the first 2 paragraph. Problem solution and problem statement is not relevant for customer.

**Comment by lagalbra** [comment]
First two paragraphs are removed; rebased against master

**Pull request merged**
