### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mabicca**
Adding more clarity about where to find workspace key on the portal.

### CODE REVIEW

**Comment by lagalbra** [comment]
@mabicca Please see our [Contributing Guide](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/CONTRIBUTING.md); we are not accepting pull requests from outside the team at this time.
Please be assured that we are actively working on improving our documentation.

**Comment by NarineM** [comment]
@lagalbra , this is a good addition and it is a small change. Can you merge this  with master?

**Comment by lagalbra** [comment]
@keikhara for FYI - this should be considered with the doc changes Matt is making

@NarineM The exact changes proposed here are not entirely clear/correct:
In the Azure portal, the workspace ID and primary key can be found under Log Analytics > <workspace> > Settings > Advanced Settings
In the OMS portal, the workspace ID and primary key can be found under Settings > Connected Sources.

The proposed changes combine parts of these two sources, but not completely correct for either portal. Docs work is still ongoing with Keiko and Matt.

**Comment by NarineM** [comment]
I am OK with just leaving Azure portal way, or actually have both. In any case I do not see any harm adding this info. Many folks who are new to omsagent onboarding experience have hard time finding these values.

**Pull request closed without merging**
