### PR TITLE
Detect VM UUID in Oracle 6 from dmi

### PR DESCRIPTION
**Pull request by canfikret**
VMUUID is showing empty GUID in omsadmin.conf in previous gen distros

### CODE REVIEW

**Comment by nidhanda** [comment]
Not sure if this is related, but when i first started, I fixed a bug with this PR #913  where if the UUID read from the omsadmin.conf is not in a valid UUID format, then I returned an empty UUID (0000-0000-....) instead of returning the invalid UUID as that was causing an issue in the portal when it displayed the UUID in logs.

**Comment by hestolz** [comment]
@nidhanda was it just UUID=<empty> or was it doubled/some other invalid value
In any case seems like before UUID wasn't even set at all on this code path so I don't think there should be any negative side effects

**Comment by canfikret** [comment]
> Not sure if this is related, but when i first started, I fixed a bug with this PR #913 where if the UUID read from the omsadmin.conf is not in a valid UUID format, then I returned an empty UUID (0000-0000-....) instead of returning the invalid UUID as that was causing an issue in the portal when it displayed the UUID in logs.

No, this orthogonal.  Your change is a fallback to GUID.Zero if the it is empty or invalid.  This PR reads it from sys.

**Comment by canfikret** [comment]
> @nidhanda was it just UUID= or was it doubled/some other invalid value
> In any case seems like before UUID wasn't even set at all on this code path so I don't think there should be any negative side effects

It was UUID=

**Pull request merged**
