### PR TITLE
doc: fix typo tcp() should be udp() 

### PR DESCRIPTION
**Pull request by abenbachir**

### CODE REVIEW

**Comment by hestolz** [comment]
Why do we want this to be UDP? Thought #899 was gonna transition us to TCP.

**Comment by abenbachir** [comment]
This is not related to syslog. Its Security Events that ASI are using through syslog (in different config [file](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/installer/conf/omsagent.d/security_events.conf)). Doc says UDP, but they put tcp() in syslog-ng.

**Comment by mgladi** [comment]
@abenbachir we're using UDP as the default since that was the case originally for the generic syslog. Are you transitioning syslog to TCP?
Thanks a lot for the fix BTW

**Comment by abenbachir** [comment]
@mgladi indeed, we are switching to TCP to handle higher loads.

**Pull request merged**
