### PR TITLE
Hotfix for Nagios/Zabbix Alert

### PR DESCRIPTION
**Pull request by sw47**
Make sure output plugin does not group empty or null records

### CODE REVIEW

**Comment by sw47** [comment]
@Microsoft/omsagent-devs Please Review

**Comment by sw47** [comment]
@Microsoft/omsagent-devs  Please Review.

Only changing alert input / filter plugins for Nagios / Zabbix. Validated on Nagios and Zabbix server. No other changes.

**Comment by jeffaco** [comment]
Nicolas has comments, so don't commit until he chimes in.

Please squash your commits down to a single commit, something like:

Bug fix: Make sure Nagios/Zabbix doesn't group up empty or null records

Do not commit the fact that you reverted a change.

If you need help with squashing, let me or Nicolas know.

Otherwise, I sign off.

**Comment by niroyb** [comment]
Also add defensive programming in the output plugin to prevent this from happening. (Ignore null records, Maybe warn once)
Otherwise signed off.

**Pull request merged**
