### PR TITLE
Squid.conf 

### PR DESCRIPTION
**Pull request by cloudtidings**
please view @Microsoft/omsagent-devs

### CODE REVIEW

**Comment by cloudtidings** [comment]
please view @Microsoft/omsagent-devs 

REGEX reviewed, tested and is now working

**Comment by robbiezhang** [comment]
can you squash the 7 commits into 1?

**Comment by cloudtidings** [comment]
Please review @robbiezhang @Microsoft/omsagent-devs 
squid1

**Comment by vrdmr** [comment]
@cloudtidings Is this PR merged or is it still open? Please close this, if github did not correctly close it when the PR was merged.

**Pull request closed without merging**
