### PR TITLE
Adding permissions for container log tail file reader

### PR DESCRIPTION
**Pull request by rashmichandrashekar**
Added permissions for containerlog tail file reader to fix the issue here - https://portal.microsofticm.com/imp/v3/incidents/details/228598287/home

### CODE REVIEW

**Review by abenbachir — APPROVED** [review]

**Comment by tobiaskohlbau** [comment]
This should fix #885 which suggest the same addition to the configuration.

**Comment by rashmichandrashekar** [comment]
@simathih @hestolz @nidhanda - could you please take a look at this PR?

**Review by nidhanda — APPROVED** [review]

**Comment by rashmichandrashekar** [comment]
@simathih @hestolz - could you pls take a look at this PR? The branch seems to be going out of date and needs merging every so often.

**Comment by hestolz** [comment]
> @simathih @hestolz - could you pls take a look at this PR? The branch seems to be going out of date and needs merging every so often.

Nikhil has approved your PR already; it is not required to get all four of our reviews

**Review by hestolz — APPROVED** [review]

**Comment by rashmichandrashekar** [comment]
> > @simathih @hestolz - could you pls take a look at this PR? The branch seems to be going out of date and needs merging every so often.
> 
> Nikhil has approved your PR already; it is not required to get all four of our reviews

Okay. Thanks. Could someone please merge the PR then?

**Pull request merged**
