### PR TITLE
Use docker image in TRAVIS-CI build

### PR DESCRIPTION
**Pull request by abenbachir**
I built a public repo for docker image using the Dokerfile.
I edited .travis.yml to pull that docker image and build OMS with --enable-ulinux.
Adding metaclass and mocha gems only when building ruby for test (not shipped with the bundle).

You can use the same docker image to build locally:

```
docker pull abenbachir/oms-centos5:2.0
docker run -i -t -v /root/OMS/Build-OMS-Agent-for-Linux:/home/scratch/Build-OMS-Agent-for-Linux abenbachir/oms-centos5:2.0 
```

### CODE REVIEW

**Comment by abenbachir** [comment]
this unit test is failing : test_apply_endpoints_file_valid() any idea why ?

**Comment by hestolz** [comment]
> this unit test is failing : test_apply_endpoints_file_valid() any idea why ?

I'm not sure, I get that same error when I run `make tests` locally. Doesn't fail on the travis machine, obviously.

**Comment by abenbachir** [comment]
Should I run "configure --enable-debug" be running the unit tests ?

**Comment by abenbachir** [comment]
I fixed the unit test by adding this group omiagent

**Comment by abenbachir** [comment]
Sometimes some NPM unitests fail with "Stream closed", when you run the tests again it pass. very weird.

**Pull request merged**
