### PR TITLE
Changes to Linux patching

### PR DESCRIPTION
**Pull request by Bpoe**
- Adding new update_management.conf for Linux patching
- Adding logrotate settings for new update_run_progress.log file used during patching
- Removing existing patching filters and cleaning up conf file, tests, etc.

This Pull Request replaces my previous one:
https://github.com/Microsoft/OMS-Agent-for-Linux/pull/411

Multi-homing is not being implemented now and will be implemented later, but before the Automation Hybrid Worker implements it post Linux Patching GA. For now, it will only work on a Primary workspace.

### CODE REVIEW

**Comment by vrdmr** [comment]
Just to confirm, this also incorporates the review comments from #411?

**Comment by Atchub** [comment]
Changes LGTM

**Comment by vrdmr** [comment]
@Bpoe - Just to know the context of the changes - The logs would now be generated by the patching runbook and you are removing all the URP components from omsagent with the change. Right?

**Comment by sugr4** [comment]
logrotate changes look fine.

**Comment by Bpoe** [comment]
Yes, this addresses the comments from 411.

I have built these changes on David and Bhaskar's build machine and it was successful.

**Pull request merged**
