### PR TITLE
Fixing regex to ignore Cisco Bug CSCve24262

### PR DESCRIPTION
**Pull request by denisyfrolov**
Some ASA are affected by a bug leads to broken format of messages. This fix allows to ignore this bug.

### CODE REVIEW

**Comment by denisyfrolov** [comment]
Issue #1078

**Comment by hestolz** [comment]
@abenbachir @Ronmarsiano can you verify this please

**Comment by Ronmarsiano** [comment]
Hi @denisyfrolov ,

the cisco scenario is based on the syslog RFC which restrict the format you provided (additional MSK timezone)

thus this fix wouldn't be accepted.

please not that you can manually configure the regex on your machines 

thanks for your contribution

**Comment by NarineM** [comment]
Change not accepted for CISCO based on syslog RFC.

**Pull request closed without merging**
