### PR TITLE
Added LogCollector tool

### PR DESCRIPTION
**Pull request by NarineM**
Added LogCollector tool to github location to be able to deliver it to customer easily  instead of using email or private dropbox location. Added source code to maintain the source code and be able to enhance it, and download package ready for use.

### CODE REVIEW

**Comment by NarineM** [comment]
@Indhukrishna;
@Microsoft/omsagent-devs

**Comment by NarineM** [comment]
@keikhara ,
Yes, I was thinking about adding markup language too. This is the initial checkin to get the tool in. Then we can work on improving the code and documentation.

**Comment by keikhara** [comment]
I understand. I created a txt version of this. Doc has very internal info of why we created log collector script. I will send it to you in a bit.

**Comment by NarineM** [comment]
@keikhara 
If you can work on converting the doc to markup language it would been very helpful. I would not be able to work on this doc till end of next week. I have made some changes to the word document , so please the GitHub version when converting to md file.

**Comment by keikhara** [comment]
Will send it to you in a bit.

**Pull request merged**
